env:
  global:
    - DOCKER_IMAGE=imduffy15/jnlp-slave
    - DOCKER_TAG=3.27-1-alpine
services:
  - docker
script:
  - docker build -t $DOCKER_IMAGE:$DOCKER_TAG-$TRAVIS_BUILD_NUMBER .
  - docker tag $DOCKER_IMAGE:$DOCKER_TAG-$TRAVIS_BUILD_NUMBER $DOCKER_IMAGE:latest
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE:$DOCKER_TAG-$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_IMAGE:latest
